version: '3.9'

services:
  neo4j:
    image: neo4j:5.10
    container_name: neo4j
    environment:
      # Authentification désactivée
      - NEO4J_AUTH=none
      # Mémoire (à ajuster selon ton Mac)
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=12G
      - NEO4J_dbms_memory_pagecache_size=8G
      # TLS désactivé
      - NEO4J_server_bolt_tls__level=DISABLED
      # Validation stricte désactivée pour éviter les erreurs
      - NEO4J_server_config_strict__validation_enabled=false
    ports:
      - "7474:7474"  # HTTP Browser
      - "7687:7687"  # Bolt
    volumes:
      - ./neo4j-data:/data