version: '3.8'

services:
  neo4j:
    image: neo4j:5-community # On utilise l'image officielle de Neo4j 5
    container_name: wikiai_neo4j
    ports:
      - "7474:7474" # Pour l'interface web (le "navigateur" Neo4j)
      - "7687:7687" # Pour la connexion depuis nos scripts Python (le "Bolt" protocol)
    volumes:
      - ./neo4j-data:/data # Persiste les données de la BDD dans un dossier local
    environment:
      # On désactive l'authentification pour faciliter le développement local
      # ATTENTION: Ne jamais faire ça pour une application en production !
      - NEO4J_AUTH=none
    restart: unless-stopped